// Auto-generated file - do not edit manually
// Generated at: 2025-09-17T10:17:09.812Z

import { GalleryWithItems } from '@/types/gallery';

export const generatedGalleries: GalleryWithItems[] = [
  {
    id: 'portrait-gallery',
    title: 'Portrait Collection',
    description: 'Beautiful portrait photography showcasing people and emotions',
    isPublic: true,
    createdAt: new Date('2025-06-03T17:13:04.316Z'),
    updatedAt: new Date('2025-06-03T17:13:04.316Z'),
    ownerId: 'mock-user-1',
    totalMemories: 15,
    storageLocations: [],
    averageStorageDuration: null,
    storageDistribution: {},
    items: [
      {
        id: 'item-portrait-gallery-0',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-1',
        memoryType: 'image',
        position: 0,
        caption: 'Photo 1',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-1',
          title: 'Photo 1',
          description: 'Beautiful photo 1 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/image_05.webp',
          createdAt: '2025-07-03T10:28:24.379Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-1',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-2',
        memoryType: 'image',
        position: 1,
        caption: 'Photo 2',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-2',
          title: 'Photo 2',
          description: 'Beautiful photo 2 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/image_11.webp',
          createdAt: '2025-09-09T13:33:59.574Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-2',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-3',
        memoryType: 'image',
        position: 2,
        caption: 'Photo 3',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-3',
          title: 'Photo 3',
          description: 'Beautiful photo 3 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/photo_01.webp',
          createdAt: '2025-05-11T02:17:47.588Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-3',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-4',
        memoryType: 'image',
        position: 3,
        caption: 'Photo 4',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-4',
          title: 'Photo 4',
          description: 'Beautiful photo 4 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/photo_06.webp',
          createdAt: '2025-05-29T22:13:36.814Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-4',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-5',
        memoryType: 'image',
        position: 4,
        caption: 'Photo 5',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-5',
          title: 'Photo 5',
          description: 'Beautiful photo 5 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/photo_08.webp',
          createdAt: '2025-08-18T23:38:36.121Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-5',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-6',
        memoryType: 'image',
        position: 5,
        caption: 'Photo 6',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-6',
          title: 'Photo 6',
          description: 'Beautiful photo 6 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/photo_12.webp',
          createdAt: '2025-05-01T06:17:51.151Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-6',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-7',
        memoryType: 'image',
        position: 6,
        caption: 'Photo 7',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-7',
          title: 'Photo 7',
          description: 'Beautiful photo 7 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/photo_13.webp',
          createdAt: '2025-03-25T04:09:00.824Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-7',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-8',
        memoryType: 'image',
        position: 7,
        caption: 'Photo 8',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-8',
          title: 'Photo 8',
          description: 'Beautiful photo 8 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/photo_15.webp',
          createdAt: '2025-03-23T06:10:49.225Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-8',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-9',
        memoryType: 'image',
        position: 8,
        caption: 'Photo 9',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-9',
          title: 'Photo 9',
          description: 'Beautiful photo 9 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/picture_03.webp',
          createdAt: '2025-09-03T21:01:41.592Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-9',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-10',
        memoryType: 'image',
        position: 9,
        caption: 'Photo 10',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-10',
          title: 'Photo 10',
          description: 'Beautiful photo 10 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/picture_07.webp',
          createdAt: '2025-05-24T05:19:42.881Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-10',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-11',
        memoryType: 'image',
        position: 10,
        caption: 'Photo 11',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-11',
          title: 'Photo 11',
          description: 'Beautiful photo 11 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/picture_10.webp',
          createdAt: '2025-09-12T04:50:32.143Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-11',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-12',
        memoryType: 'image',
        position: 11,
        caption: 'Photo 12',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-12',
          title: 'Photo 12',
          description: 'Beautiful photo 12 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/picture_14.webp',
          createdAt: '2025-08-05T10:13:39.617Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-12',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-13',
        memoryType: 'image',
        position: 12,
        caption: 'Photo 13',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-13',
          title: 'Photo 13',
          description: 'Beautiful photo 13 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/shot_02.webp',
          createdAt: '2025-05-19T10:36:30.608Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-13',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-14',
        memoryType: 'image',
        position: 13,
        caption: 'Photo 14',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-14',
          title: 'Photo 14',
          description: 'Beautiful photo 14 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/shot_04.webp',
          createdAt: '2025-06-02T16:44:11.177Z',
          metadata: {},
        },
      },
      {
        id: 'item-portrait-gallery-14',
        galleryId: 'portrait-gallery',
        memoryId: 'memory-portrait-gallery-15',
        memoryType: 'image',
        position: 14,
        caption: 'Photo 15',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-06-03T17:13:04.316Z'),
        updatedAt: new Date('2025-06-03T17:13:04.316Z'),
        memory: {
          id: 'memory-portrait-gallery-15',
          title: 'Photo 15',
          description: 'Beautiful photo 15 from Portrait Collection',
          type: 'image',
          url: '/mock/galleries/portrait-gallery/shot_09.webp',
          createdAt: '2025-07-08T23:06:22.694Z',
          metadata: {},
        },
      },
    ],
    imageCount: 15,
    isOwner: true,
  },
  {
    id: 'landscape-gallery',
    title: 'Landscape Photography',
    description: 'Stunning landscapes from around the world',
    isPublic: true,
    createdAt: new Date('2025-07-26T06:28:20.069Z'),
    updatedAt: new Date('2025-07-26T06:28:20.069Z'),
    ownerId: 'mock-user-1',
    totalMemories: 15,
    storageLocations: [],
    averageStorageDuration: null,
    storageDistribution: {},
    items: [
      {
        id: 'item-landscape-gallery-0',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-1',
        memoryType: 'image',
        position: 0,
        caption: 'Photo 1',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-1',
          title: 'Photo 1',
          description: 'Beautiful photo 1 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/image_03.webp',
          createdAt: '2025-06-08T12:25:04.262Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-1',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-2',
        memoryType: 'image',
        position: 1,
        caption: 'Photo 2',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-2',
          title: 'Photo 2',
          description: 'Beautiful photo 2 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/image_11.webp',
          createdAt: '2025-08-23T07:40:10.927Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-2',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-3',
        memoryType: 'image',
        position: 2,
        caption: 'Photo 3',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-3',
          title: 'Photo 3',
          description: 'Beautiful photo 3 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/image_12.webp',
          createdAt: '2025-08-03T18:21:33.003Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-3',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-4',
        memoryType: 'image',
        position: 3,
        caption: 'Photo 4',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-4',
          title: 'Photo 4',
          description: 'Beautiful photo 4 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/photo_13.webp',
          createdAt: '2025-08-07T17:43:38.063Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-4',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-5',
        memoryType: 'image',
        position: 4,
        caption: 'Photo 5',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-5',
          title: 'Photo 5',
          description: 'Beautiful photo 5 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/photo_15.webp',
          createdAt: '2025-06-08T15:21:41.567Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-5',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-6',
        memoryType: 'image',
        position: 5,
        caption: 'Photo 6',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-6',
          title: 'Photo 6',
          description: 'Beautiful photo 6 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/picture_04.webp',
          createdAt: '2025-04-18T08:43:13.805Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-6',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-7',
        memoryType: 'image',
        position: 6,
        caption: 'Photo 7',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-7',
          title: 'Photo 7',
          description: 'Beautiful photo 7 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/picture_05.webp',
          createdAt: '2025-07-07T05:31:11.580Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-7',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-8',
        memoryType: 'image',
        position: 7,
        caption: 'Photo 8',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-8',
          title: 'Photo 8',
          description: 'Beautiful photo 8 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/picture_06.webp',
          createdAt: '2025-04-17T00:00:31.425Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-8',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-9',
        memoryType: 'image',
        position: 8,
        caption: 'Photo 9',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-9',
          title: 'Photo 9',
          description: 'Beautiful photo 9 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/picture_10.webp',
          createdAt: '2025-05-25T17:38:19.149Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-9',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-10',
        memoryType: 'image',
        position: 9,
        caption: 'Photo 10',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-10',
          title: 'Photo 10',
          description: 'Beautiful photo 10 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/shot_01.webp',
          createdAt: '2025-04-16T14:36:08.702Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-10',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-11',
        memoryType: 'image',
        position: 10,
        caption: 'Photo 11',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-11',
          title: 'Photo 11',
          description: 'Beautiful photo 11 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/shot_02.webp',
          createdAt: '2025-06-11T04:47:09.840Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-11',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-12',
        memoryType: 'image',
        position: 11,
        caption: 'Photo 12',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-12',
          title: 'Photo 12',
          description: 'Beautiful photo 12 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/shot_07.webp',
          createdAt: '2025-07-06T00:16:31.673Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-12',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-13',
        memoryType: 'image',
        position: 12,
        caption: 'Photo 13',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-13',
          title: 'Photo 13',
          description: 'Beautiful photo 13 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/shot_08.webp',
          createdAt: '2025-04-03T08:28:59.218Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-13',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-14',
        memoryType: 'image',
        position: 13,
        caption: 'Photo 14',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-14',
          title: 'Photo 14',
          description: 'Beautiful photo 14 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/shot_09.webp',
          createdAt: '2025-03-31T18:34:36.003Z',
          metadata: {},
        },
      },
      {
        id: 'item-landscape-gallery-14',
        galleryId: 'landscape-gallery',
        memoryId: 'memory-landscape-gallery-15',
        memoryType: 'image',
        position: 14,
        caption: 'Photo 15',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-26T06:28:20.069Z'),
        updatedAt: new Date('2025-07-26T06:28:20.069Z'),
        memory: {
          id: 'memory-landscape-gallery-15',
          title: 'Photo 15',
          description: 'Beautiful photo 15 from Landscape Photography',
          type: 'image',
          url: '/mock/galleries/landscape-gallery/shot_14.webp',
          createdAt: '2025-05-30T16:07:41.036Z',
          metadata: {},
        },
      },
    ],
    imageCount: 15,
    isOwner: true,
  },
  {
    id: 'mixed-gallery',
    title: 'Mixed Media Gallery',
    description: 'A diverse collection of different photography styles',
    isPublic: false,
    createdAt: new Date('2025-07-31T10:09:15.152Z'),
    updatedAt: new Date('2025-07-31T10:09:15.152Z'),
    ownerId: 'mock-user-1',
    totalMemories: 20,
    storageLocations: [],
    averageStorageDuration: null,
    storageDistribution: {},
    items: [
      {
        id: 'item-mixed-gallery-0',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-1',
        memoryType: 'image',
        position: 0,
        caption: 'Photo 1',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-1',
          title: 'Photo 1',
          description: 'Beautiful photo 1 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_01.webp',
          createdAt: '2025-08-23T01:54:17.742Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-1',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-2',
        memoryType: 'image',
        position: 1,
        caption: 'Photo 2',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-2',
          title: 'Photo 2',
          description: 'Beautiful photo 2 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_04.webp',
          createdAt: '2025-06-08T19:14:00.624Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-2',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-3',
        memoryType: 'image',
        position: 2,
        caption: 'Photo 3',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-3',
          title: 'Photo 3',
          description: 'Beautiful photo 3 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_05.webp',
          createdAt: '2025-06-10T20:54:14.863Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-3',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-4',
        memoryType: 'image',
        position: 3,
        caption: 'Photo 4',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-4',
          title: 'Photo 4',
          description: 'Beautiful photo 4 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_08.webp',
          createdAt: '2025-05-19T04:46:12.278Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-4',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-5',
        memoryType: 'image',
        position: 4,
        caption: 'Photo 5',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-5',
          title: 'Photo 5',
          description: 'Beautiful photo 5 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_10.webp',
          createdAt: '2025-06-16T13:55:10.290Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-5',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-6',
        memoryType: 'image',
        position: 5,
        caption: 'Photo 6',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-6',
          title: 'Photo 6',
          description: 'Beautiful photo 6 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_13.webp',
          createdAt: '2025-05-29T09:59:52.019Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-6',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-7',
        memoryType: 'image',
        position: 6,
        caption: 'Photo 7',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-7',
          title: 'Photo 7',
          description: 'Beautiful photo 7 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_18.webp',
          createdAt: '2025-05-24T13:42:33.124Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-7',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-8',
        memoryType: 'image',
        position: 7,
        caption: 'Photo 8',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-8',
          title: 'Photo 8',
          description: 'Beautiful photo 8 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/image_19.webp',
          createdAt: '2025-05-26T16:42:20.080Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-8',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-9',
        memoryType: 'image',
        position: 8,
        caption: 'Photo 9',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-9',
          title: 'Photo 9',
          description: 'Beautiful photo 9 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/photo_20.webp',
          createdAt: '2025-06-19T15:49:31.787Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-9',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-10',
        memoryType: 'image',
        position: 9,
        caption: 'Photo 10',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-10',
          title: 'Photo 10',
          description: 'Beautiful photo 10 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/picture_02.webp',
          createdAt: '2025-08-06T03:24:52.620Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-10',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-11',
        memoryType: 'image',
        position: 10,
        caption: 'Photo 11',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-11',
          title: 'Photo 11',
          description: 'Beautiful photo 11 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/picture_06.webp',
          createdAt: '2025-06-13T19:50:26.939Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-11',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-12',
        memoryType: 'image',
        position: 11,
        caption: 'Photo 12',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-12',
          title: 'Photo 12',
          description: 'Beautiful photo 12 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/picture_15.webp',
          createdAt: '2025-08-27T11:42:30.929Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-12',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-13',
        memoryType: 'image',
        position: 12,
        caption: 'Photo 13',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-13',
          title: 'Photo 13',
          description: 'Beautiful photo 13 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/picture_16.webp',
          createdAt: '2025-07-20T14:58:23.475Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-13',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-14',
        memoryType: 'image',
        position: 13,
        caption: 'Photo 14',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-14',
          title: 'Photo 14',
          description: 'Beautiful photo 14 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/picture_17.webp',
          createdAt: '2025-03-29T21:10:05.918Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-14',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-15',
        memoryType: 'image',
        position: 14,
        caption: 'Photo 15',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-15',
          title: 'Photo 15',
          description: 'Beautiful photo 15 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/shot_03.webp',
          createdAt: '2025-06-26T03:24:25.805Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-15',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-16',
        memoryType: 'image',
        position: 15,
        caption: 'Photo 16',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-16',
          title: 'Photo 16',
          description: 'Beautiful photo 16 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/shot_07.webp',
          createdAt: '2025-03-31T20:31:48.010Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-16',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-17',
        memoryType: 'image',
        position: 16,
        caption: 'Photo 17',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-17',
          title: 'Photo 17',
          description: 'Beautiful photo 17 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/shot_09.webp',
          createdAt: '2025-08-10T20:40:30.624Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-17',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-18',
        memoryType: 'image',
        position: 17,
        caption: 'Photo 18',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-18',
          title: 'Photo 18',
          description: 'Beautiful photo 18 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/shot_11.webp',
          createdAt: '2025-07-06T20:14:24.560Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-18',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-19',
        memoryType: 'image',
        position: 18,
        caption: 'Photo 19',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-19',
          title: 'Photo 19',
          description: 'Beautiful photo 19 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/shot_12.webp',
          createdAt: '2025-08-21T01:30:27.027Z',
          metadata: {},
        },
      },
      {
        id: 'item-mixed-gallery-19',
        galleryId: 'mixed-gallery',
        memoryId: 'memory-mixed-gallery-20',
        memoryType: 'image',
        position: 19,
        caption: 'Photo 20',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-07-31T10:09:15.152Z'),
        updatedAt: new Date('2025-07-31T10:09:15.152Z'),
        memory: {
          id: 'memory-mixed-gallery-20',
          title: 'Photo 20',
          description: 'Beautiful photo 20 from Mixed Media Gallery',
          type: 'image',
          url: '/mock/galleries/mixed-gallery/shot_14.webp',
          createdAt: '2025-07-02T05:26:40.740Z',
          metadata: {},
        },
      },
    ],
    imageCount: 20,
    isOwner: true,
  },
  {
    id: 'wild-gallery',
    title: 'Wild & Free',
    description: 'Adventure and nature photography',
    isPublic: true,
    createdAt: new Date('2025-04-15T16:27:16.274Z'),
    updatedAt: new Date('2025-04-15T16:27:16.274Z'),
    ownerId: 'mock-user-1',
    totalMemories: 25,
    storageLocations: [],
    averageStorageDuration: null,
    storageDistribution: {},
    items: [
      {
        id: 'item-wild-gallery-0',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-1',
        memoryType: 'image',
        position: 0,
        caption: 'Photo 1',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-1',
          title: 'Photo 1',
          description: 'Beautiful photo 1 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/image_03.webp',
          createdAt: '2025-05-30T16:14:59.168Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-1',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-2',
        memoryType: 'image',
        position: 1,
        caption: 'Photo 2',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-2',
          title: 'Photo 2',
          description: 'Beautiful photo 2 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/image_04.webp',
          createdAt: '2025-06-25T19:40:24.444Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-2',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-3',
        memoryType: 'image',
        position: 2,
        caption: 'Photo 3',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-3',
          title: 'Photo 3',
          description: 'Beautiful photo 3 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/image_06.webp',
          createdAt: '2025-05-06T00:05:57.500Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-3',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-4',
        memoryType: 'image',
        position: 3,
        caption: 'Photo 4',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-4',
          title: 'Photo 4',
          description: 'Beautiful photo 4 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/image_09.webp',
          createdAt: '2025-08-25T05:59:01.561Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-4',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-5',
        memoryType: 'image',
        position: 4,
        caption: 'Photo 5',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-5',
          title: 'Photo 5',
          description: 'Beautiful photo 5 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/image_16.webp',
          createdAt: '2025-06-25T13:33:14.608Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-5',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-6',
        memoryType: 'image',
        position: 5,
        caption: 'Photo 6',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-6',
          title: 'Photo 6',
          description: 'Beautiful photo 6 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/image_21.webp',
          createdAt: '2025-04-17T00:11:23.720Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-6',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-7',
        memoryType: 'image',
        position: 6,
        caption: 'Photo 7',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-7',
          title: 'Photo 7',
          description: 'Beautiful photo 7 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/image_24.webp',
          createdAt: '2025-06-25T20:17:37.252Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-7',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-8',
        memoryType: 'image',
        position: 7,
        caption: 'Photo 8',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-8',
          title: 'Photo 8',
          description: 'Beautiful photo 8 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/photo_01.webp',
          createdAt: '2025-09-07T18:38:19.184Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-8',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-9',
        memoryType: 'image',
        position: 8,
        caption: 'Photo 9',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-9',
          title: 'Photo 9',
          description: 'Beautiful photo 9 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/photo_13.webp',
          createdAt: '2025-07-12T17:46:22.736Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-9',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-10',
        memoryType: 'image',
        position: 9,
        caption: 'Photo 10',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-10',
          title: 'Photo 10',
          description: 'Beautiful photo 10 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/photo_17.webp',
          createdAt: '2025-07-23T17:38:59.424Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-10',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-11',
        memoryType: 'image',
        position: 10,
        caption: 'Photo 11',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-11',
          title: 'Photo 11',
          description: 'Beautiful photo 11 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/photo_18.webp',
          createdAt: '2025-09-05T15:32:50.442Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-11',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-12',
        memoryType: 'image',
        position: 11,
        caption: 'Photo 12',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-12',
          title: 'Photo 12',
          description: 'Beautiful photo 12 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_07.webp',
          createdAt: '2025-04-16T22:59:24.958Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-12',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-13',
        memoryType: 'image',
        position: 12,
        caption: 'Photo 13',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-13',
          title: 'Photo 13',
          description: 'Beautiful photo 13 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_08.webp',
          createdAt: '2025-06-24T00:23:36.325Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-13',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-14',
        memoryType: 'image',
        position: 13,
        caption: 'Photo 14',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-14',
          title: 'Photo 14',
          description: 'Beautiful photo 14 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_10.webp',
          createdAt: '2025-06-21T12:44:04.154Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-14',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-15',
        memoryType: 'image',
        position: 14,
        caption: 'Photo 15',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-15',
          title: 'Photo 15',
          description: 'Beautiful photo 15 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_11.webp',
          createdAt: '2025-04-02T00:25:48.209Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-15',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-16',
        memoryType: 'image',
        position: 15,
        caption: 'Photo 16',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-16',
          title: 'Photo 16',
          description: 'Beautiful photo 16 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_12.webp',
          createdAt: '2025-06-05T06:31:38.370Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-16',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-17',
        memoryType: 'image',
        position: 16,
        caption: 'Photo 17',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-17',
          title: 'Photo 17',
          description: 'Beautiful photo 17 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_14.webp',
          createdAt: '2025-08-01T22:51:40.371Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-17',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-18',
        memoryType: 'image',
        position: 17,
        caption: 'Photo 18',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-18',
          title: 'Photo 18',
          description: 'Beautiful photo 18 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_15.webp',
          createdAt: '2025-04-28T09:11:16.342Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-18',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-19',
        memoryType: 'image',
        position: 18,
        caption: 'Photo 19',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-19',
          title: 'Photo 19',
          description: 'Beautiful photo 19 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_20.webp',
          createdAt: '2025-05-19T09:25:58.884Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-19',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-20',
        memoryType: 'image',
        position: 19,
        caption: 'Photo 20',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-20',
          title: 'Photo 20',
          description: 'Beautiful photo 20 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_22.webp',
          createdAt: '2025-05-15T19:34:20.817Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-20',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-21',
        memoryType: 'image',
        position: 20,
        caption: 'Photo 21',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-21',
          title: 'Photo 21',
          description: 'Beautiful photo 21 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/picture_23.webp',
          createdAt: '2025-07-22T07:23:29.236Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-21',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-22',
        memoryType: 'image',
        position: 21,
        caption: 'Photo 22',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-22',
          title: 'Photo 22',
          description: 'Beautiful photo 22 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/shot_02.webp',
          createdAt: '2025-06-12T12:48:19.729Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-22',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-23',
        memoryType: 'image',
        position: 22,
        caption: 'Photo 23',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-23',
          title: 'Photo 23',
          description: 'Beautiful photo 23 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/shot_05.webp',
          createdAt: '2025-07-22T02:48:04.599Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-23',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-24',
        memoryType: 'image',
        position: 23,
        caption: 'Photo 24',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-24',
          title: 'Photo 24',
          description: 'Beautiful photo 24 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/shot_19.webp',
          createdAt: '2025-09-14T16:08:01.843Z',
          metadata: {},
        },
      },
      {
        id: 'item-wild-gallery-24',
        galleryId: 'wild-gallery',
        memoryId: 'memory-wild-gallery-25',
        memoryType: 'image',
        position: 24,
        caption: 'Photo 25',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-04-15T16:27:16.274Z'),
        updatedAt: new Date('2025-04-15T16:27:16.274Z'),
        memory: {
          id: 'memory-wild-gallery-25',
          title: 'Photo 25',
          description: 'Beautiful photo 25 from Wild & Free',
          type: 'image',
          url: '/mock/galleries/wild-gallery/shot_25.webp',
          createdAt: '2025-08-06T06:47:09.404Z',
          metadata: {},
        },
      },
    ],
    imageCount: 25,
    isOwner: true,
  },
  {
    id: 'small-gallery',
    title: 'Small Moments',
    description: 'Intimate moments captured in time',
    isPublic: false,
    createdAt: new Date('2025-08-02T06:48:54.055Z'),
    updatedAt: new Date('2025-08-02T06:48:54.055Z'),
    ownerId: 'mock-user-1',
    totalMemories: 5,
    storageLocations: [],
    averageStorageDuration: null,
    storageDistribution: {},
    items: [
      {
        id: 'item-small-gallery-0',
        galleryId: 'small-gallery',
        memoryId: 'memory-small-gallery-1',
        memoryType: 'image',
        position: 0,
        caption: 'Photo 1',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-02T06:48:54.055Z'),
        updatedAt: new Date('2025-08-02T06:48:54.055Z'),
        memory: {
          id: 'memory-small-gallery-1',
          title: 'Photo 1',
          description: 'Beautiful photo 1 from Small Moments',
          type: 'image',
          url: '/mock/galleries/small-gallery/photo_02.webp',
          createdAt: '2025-06-06T05:48:20.513Z',
          metadata: {},
        },
      },
      {
        id: 'item-small-gallery-1',
        galleryId: 'small-gallery',
        memoryId: 'memory-small-gallery-2',
        memoryType: 'image',
        position: 1,
        caption: 'Photo 2',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-02T06:48:54.055Z'),
        updatedAt: new Date('2025-08-02T06:48:54.055Z'),
        memory: {
          id: 'memory-small-gallery-2',
          title: 'Photo 2',
          description: 'Beautiful photo 2 from Small Moments',
          type: 'image',
          url: '/mock/galleries/small-gallery/photo_03.webp',
          createdAt: '2025-03-24T07:25:08.371Z',
          metadata: {},
        },
      },
      {
        id: 'item-small-gallery-2',
        galleryId: 'small-gallery',
        memoryId: 'memory-small-gallery-3',
        memoryType: 'image',
        position: 2,
        caption: 'Photo 3',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-02T06:48:54.055Z'),
        updatedAt: new Date('2025-08-02T06:48:54.055Z'),
        memory: {
          id: 'memory-small-gallery-3',
          title: 'Photo 3',
          description: 'Beautiful photo 3 from Small Moments',
          type: 'image',
          url: '/mock/galleries/small-gallery/photo_04.webp',
          createdAt: '2025-09-01T22:17:31.797Z',
          metadata: {},
        },
      },
      {
        id: 'item-small-gallery-3',
        galleryId: 'small-gallery',
        memoryId: 'memory-small-gallery-4',
        memoryType: 'image',
        position: 3,
        caption: 'Photo 4',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-02T06:48:54.055Z'),
        updatedAt: new Date('2025-08-02T06:48:54.055Z'),
        memory: {
          id: 'memory-small-gallery-4',
          title: 'Photo 4',
          description: 'Beautiful photo 4 from Small Moments',
          type: 'image',
          url: '/mock/galleries/small-gallery/picture_05.webp',
          createdAt: '2025-05-18T22:01:04.176Z',
          metadata: {},
        },
      },
      {
        id: 'item-small-gallery-4',
        galleryId: 'small-gallery',
        memoryId: 'memory-small-gallery-5',
        memoryType: 'image',
        position: 4,
        caption: 'Photo 5',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-02T06:48:54.055Z'),
        updatedAt: new Date('2025-08-02T06:48:54.055Z'),
        memory: {
          id: 'memory-small-gallery-5',
          title: 'Photo 5',
          description: 'Beautiful photo 5 from Small Moments',
          type: 'image',
          url: '/mock/galleries/small-gallery/shot_01.webp',
          createdAt: '2025-03-27T13:32:31.236Z',
          metadata: {},
        },
      },
    ],
    imageCount: 5,
    isOwner: true,
  },
  {
    id: 'large-gallery',
    title: 'Large Collection',
    description: 'An extensive collection of memories',
    isPublic: true,
    createdAt: new Date('2025-08-21T16:22:17.316Z'),
    updatedAt: new Date('2025-08-21T16:22:17.316Z'),
    ownerId: 'mock-user-1',
    totalMemories: 50,
    storageLocations: [],
    averageStorageDuration: null,
    storageDistribution: {},
    items: [
      {
        id: 'item-large-gallery-0',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-1',
        memoryType: 'image',
        position: 0,
        caption: 'Photo 1',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-1',
          title: 'Photo 1',
          description: 'Beautiful photo 1 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_05.webp',
          createdAt: '2025-05-12T22:00:44.025Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-1',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-2',
        memoryType: 'image',
        position: 1,
        caption: 'Photo 2',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-2',
          title: 'Photo 2',
          description: 'Beautiful photo 2 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_13.webp',
          createdAt: '2025-09-01T02:51:44.349Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-2',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-3',
        memoryType: 'image',
        position: 2,
        caption: 'Photo 3',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-3',
          title: 'Photo 3',
          description: 'Beautiful photo 3 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_16.webp',
          createdAt: '2025-05-05T09:32:57.961Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-3',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-4',
        memoryType: 'image',
        position: 3,
        caption: 'Photo 4',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-4',
          title: 'Photo 4',
          description: 'Beautiful photo 4 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_20.webp',
          createdAt: '2025-05-31T23:07:41.353Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-4',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-5',
        memoryType: 'image',
        position: 4,
        caption: 'Photo 5',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-5',
          title: 'Photo 5',
          description: 'Beautiful photo 5 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_28.webp',
          createdAt: '2025-09-03T11:28:15.736Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-5',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-6',
        memoryType: 'image',
        position: 5,
        caption: 'Photo 6',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-6',
          title: 'Photo 6',
          description: 'Beautiful photo 6 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_32.webp',
          createdAt: '2025-08-23T06:13:47.748Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-6',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-7',
        memoryType: 'image',
        position: 6,
        caption: 'Photo 7',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-7',
          title: 'Photo 7',
          description: 'Beautiful photo 7 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_38.webp',
          createdAt: '2025-08-17T05:04:16.044Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-7',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-8',
        memoryType: 'image',
        position: 7,
        caption: 'Photo 8',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-8',
          title: 'Photo 8',
          description: 'Beautiful photo 8 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_41.webp',
          createdAt: '2025-07-04T18:36:42.389Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-8',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-9',
        memoryType: 'image',
        position: 8,
        caption: 'Photo 9',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-9',
          title: 'Photo 9',
          description: 'Beautiful photo 9 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_45.webp',
          createdAt: '2025-03-26T10:49:44.547Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-9',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-10',
        memoryType: 'image',
        position: 9,
        caption: 'Photo 10',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-10',
          title: 'Photo 10',
          description: 'Beautiful photo 10 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/image_49.webp',
          createdAt: '2025-09-06T09:36:53.273Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-10',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-11',
        memoryType: 'image',
        position: 10,
        caption: 'Photo 11',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-11',
          title: 'Photo 11',
          description: 'Beautiful photo 11 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_01.webp',
          createdAt: '2025-09-11T06:21:46.971Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-11',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-12',
        memoryType: 'image',
        position: 11,
        caption: 'Photo 12',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-12',
          title: 'Photo 12',
          description: 'Beautiful photo 12 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_04.webp',
          createdAt: '2025-07-26T07:52:18.011Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-12',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-13',
        memoryType: 'image',
        position: 12,
        caption: 'Photo 13',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-13',
          title: 'Photo 13',
          description: 'Beautiful photo 13 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_07.webp',
          createdAt: '2025-04-28T16:55:49.572Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-13',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-14',
        memoryType: 'image',
        position: 13,
        caption: 'Photo 14',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-14',
          title: 'Photo 14',
          description: 'Beautiful photo 14 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_08.webp',
          createdAt: '2025-06-28T03:29:28.252Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-14',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-15',
        memoryType: 'image',
        position: 14,
        caption: 'Photo 15',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-15',
          title: 'Photo 15',
          description: 'Beautiful photo 15 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_10.webp',
          createdAt: '2025-06-08T17:44:34.808Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-15',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-16',
        memoryType: 'image',
        position: 15,
        caption: 'Photo 16',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-16',
          title: 'Photo 16',
          description: 'Beautiful photo 16 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_18.webp',
          createdAt: '2025-04-08T10:01:04.084Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-16',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-17',
        memoryType: 'image',
        position: 16,
        caption: 'Photo 17',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-17',
          title: 'Photo 17',
          description: 'Beautiful photo 17 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_24.webp',
          createdAt: '2025-08-28T09:18:14.519Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-17',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-18',
        memoryType: 'image',
        position: 17,
        caption: 'Photo 18',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-18',
          title: 'Photo 18',
          description: 'Beautiful photo 18 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_25.webp',
          createdAt: '2025-06-19T23:17:24.608Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-18',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-19',
        memoryType: 'image',
        position: 18,
        caption: 'Photo 19',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-19',
          title: 'Photo 19',
          description: 'Beautiful photo 19 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_26.webp',
          createdAt: '2025-08-30T22:41:37.447Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-19',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-20',
        memoryType: 'image',
        position: 19,
        caption: 'Photo 20',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-20',
          title: 'Photo 20',
          description: 'Beautiful photo 20 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_30.webp',
          createdAt: '2025-08-01T02:18:55.619Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-20',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-21',
        memoryType: 'image',
        position: 20,
        caption: 'Photo 21',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-21',
          title: 'Photo 21',
          description: 'Beautiful photo 21 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_33.webp',
          createdAt: '2025-04-06T14:05:12.389Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-21',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-22',
        memoryType: 'image',
        position: 21,
        caption: 'Photo 22',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-22',
          title: 'Photo 22',
          description: 'Beautiful photo 22 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_34.webp',
          createdAt: '2025-07-16T13:59:10.113Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-22',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-23',
        memoryType: 'image',
        position: 22,
        caption: 'Photo 23',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-23',
          title: 'Photo 23',
          description: 'Beautiful photo 23 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_36.webp',
          createdAt: '2025-07-01T11:23:40.603Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-23',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-24',
        memoryType: 'image',
        position: 23,
        caption: 'Photo 24',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-24',
          title: 'Photo 24',
          description: 'Beautiful photo 24 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_44.webp',
          createdAt: '2025-08-02T03:36:46.262Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-24',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-25',
        memoryType: 'image',
        position: 24,
        caption: 'Photo 25',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-25',
          title: 'Photo 25',
          description: 'Beautiful photo 25 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/photo_46.webp',
          createdAt: '2025-06-24T21:16:02.864Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-25',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-26',
        memoryType: 'image',
        position: 25,
        caption: 'Photo 26',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-26',
          title: 'Photo 26',
          description: 'Beautiful photo 26 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_03.webp',
          createdAt: '2025-08-21T02:21:56.315Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-26',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-27',
        memoryType: 'image',
        position: 26,
        caption: 'Photo 27',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-27',
          title: 'Photo 27',
          description: 'Beautiful photo 27 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_09.webp',
          createdAt: '2025-05-01T23:25:57.097Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-27',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-28',
        memoryType: 'image',
        position: 27,
        caption: 'Photo 28',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-28',
          title: 'Photo 28',
          description: 'Beautiful photo 28 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_12.webp',
          createdAt: '2025-06-09T23:24:41.890Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-28',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-29',
        memoryType: 'image',
        position: 28,
        caption: 'Photo 29',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-29',
          title: 'Photo 29',
          description: 'Beautiful photo 29 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_14.webp',
          createdAt: '2025-04-13T05:22:04.147Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-29',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-30',
        memoryType: 'image',
        position: 29,
        caption: 'Photo 30',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-30',
          title: 'Photo 30',
          description: 'Beautiful photo 30 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_15.webp',
          createdAt: '2025-07-04T22:04:41.586Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-30',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-31',
        memoryType: 'image',
        position: 30,
        caption: 'Photo 31',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-31',
          title: 'Photo 31',
          description: 'Beautiful photo 31 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_19.webp',
          createdAt: '2025-07-30T21:22:54.049Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-31',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-32',
        memoryType: 'image',
        position: 31,
        caption: 'Photo 32',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-32',
          title: 'Photo 32',
          description: 'Beautiful photo 32 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_21.webp',
          createdAt: '2025-08-16T09:12:55.619Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-32',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-33',
        memoryType: 'image',
        position: 32,
        caption: 'Photo 33',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-33',
          title: 'Photo 33',
          description: 'Beautiful photo 33 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_22.webp',
          createdAt: '2025-07-20T22:22:14.538Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-33',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-34',
        memoryType: 'image',
        position: 33,
        caption: 'Photo 34',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-34',
          title: 'Photo 34',
          description: 'Beautiful photo 34 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_27.webp',
          createdAt: '2025-05-15T16:13:45.073Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-34',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-35',
        memoryType: 'image',
        position: 34,
        caption: 'Photo 35',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-35',
          title: 'Photo 35',
          description: 'Beautiful photo 35 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_29.webp',
          createdAt: '2025-05-11T11:09:29.279Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-35',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-36',
        memoryType: 'image',
        position: 35,
        caption: 'Photo 36',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-36',
          title: 'Photo 36',
          description: 'Beautiful photo 36 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_39.webp',
          createdAt: '2025-08-03T23:30:33.088Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-36',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-37',
        memoryType: 'image',
        position: 36,
        caption: 'Photo 37',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-37',
          title: 'Photo 37',
          description: 'Beautiful photo 37 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_42.webp',
          createdAt: '2025-07-24T05:08:15.946Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-37',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-38',
        memoryType: 'image',
        position: 37,
        caption: 'Photo 38',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-38',
          title: 'Photo 38',
          description: 'Beautiful photo 38 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_43.webp',
          createdAt: '2025-04-28T21:42:00.457Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-38',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-39',
        memoryType: 'image',
        position: 38,
        caption: 'Photo 39',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-39',
          title: 'Photo 39',
          description: 'Beautiful photo 39 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_47.webp',
          createdAt: '2025-05-03T14:34:37.762Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-39',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-40',
        memoryType: 'image',
        position: 39,
        caption: 'Photo 40',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-40',
          title: 'Photo 40',
          description: 'Beautiful photo 40 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_48.webp',
          createdAt: '2025-08-08T11:38:18.101Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-40',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-41',
        memoryType: 'image',
        position: 40,
        caption: 'Photo 41',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-41',
          title: 'Photo 41',
          description: 'Beautiful photo 41 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/picture_50.webp',
          createdAt: '2025-06-23T23:05:46.592Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-41',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-42',
        memoryType: 'image',
        position: 41,
        caption: 'Photo 42',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-42',
          title: 'Photo 42',
          description: 'Beautiful photo 42 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_02.webp',
          createdAt: '2025-08-25T12:17:09.240Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-42',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-43',
        memoryType: 'image',
        position: 42,
        caption: 'Photo 43',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-43',
          title: 'Photo 43',
          description: 'Beautiful photo 43 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_06.webp',
          createdAt: '2025-04-19T16:54:16.777Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-43',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-44',
        memoryType: 'image',
        position: 43,
        caption: 'Photo 44',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-44',
          title: 'Photo 44',
          description: 'Beautiful photo 44 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_11.webp',
          createdAt: '2025-07-25T22:59:38.201Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-44',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-45',
        memoryType: 'image',
        position: 44,
        caption: 'Photo 45',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-45',
          title: 'Photo 45',
          description: 'Beautiful photo 45 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_17.webp',
          createdAt: '2025-03-23T21:58:39.590Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-45',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-46',
        memoryType: 'image',
        position: 45,
        caption: 'Photo 46',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-46',
          title: 'Photo 46',
          description: 'Beautiful photo 46 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_23.webp',
          createdAt: '2025-08-29T08:11:38.184Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-46',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-47',
        memoryType: 'image',
        position: 46,
        caption: 'Photo 47',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-47',
          title: 'Photo 47',
          description: 'Beautiful photo 47 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_31.webp',
          createdAt: '2025-05-16T10:21:13.613Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-47',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-48',
        memoryType: 'image',
        position: 47,
        caption: 'Photo 48',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-48',
          title: 'Photo 48',
          description: 'Beautiful photo 48 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_35.webp',
          createdAt: '2025-07-03T02:10:44.913Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-48',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-49',
        memoryType: 'image',
        position: 48,
        caption: 'Photo 49',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-49',
          title: 'Photo 49',
          description: 'Beautiful photo 49 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_37.webp',
          createdAt: '2025-08-17T17:43:23.981Z',
          metadata: {},
        },
      },
      {
        id: 'item-large-gallery-49',
        galleryId: 'large-gallery',
        memoryId: 'memory-large-gallery-50',
        memoryType: 'image',
        position: 49,
        caption: 'Photo 50',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-21T16:22:17.316Z'),
        updatedAt: new Date('2025-08-21T16:22:17.316Z'),
        memory: {
          id: 'memory-large-gallery-50',
          title: 'Photo 50',
          description: 'Beautiful photo 50 from Large Collection',
          type: 'image',
          url: '/mock/galleries/large-gallery/shot_40.webp',
          createdAt: '2025-09-05T01:03:36.786Z',
          metadata: {},
        },
      },
    ],
    imageCount: 50,
    isOwner: true,
  },
  {
    id: 'broken-gallery',
    title: 'Broken Links Gallery',
    description: 'Testing fallback behavior with broken image links',
    isPublic: true,
    createdAt: new Date('2025-08-30T06:15:23.931Z'),
    updatedAt: new Date('2025-08-30T06:15:23.931Z'),
    ownerId: 'mock-user-1',
    totalMemories: 5,
    storageLocations: [],
    averageStorageDuration: null,
    storageDistribution: {},
    items: [
      {
        id: 'item-broken-gallery-0',
        galleryId: 'broken-gallery',
        memoryId: 'memory-broken-gallery-1',
        memoryType: 'image',
        position: 0,
        caption: 'Photo 1',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-30T06:15:23.931Z'),
        updatedAt: new Date('2025-08-30T06:15:23.931Z'),
        memory: {
          id: 'memory-broken-gallery-1',
          title: 'Photo 1',
          description: 'Beautiful photo 1 from Broken Links Gallery',
          type: 'image',
          url: '/mock/galleries/broken-gallery/broken_image_1.webp',
          createdAt: '2025-05-19T08:20:49.844Z',
          metadata: {},
        },
      },
      {
        id: 'item-broken-gallery-1',
        galleryId: 'broken-gallery',
        memoryId: 'memory-broken-gallery-2',
        memoryType: 'image',
        position: 1,
        caption: 'Photo 2',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-30T06:15:23.931Z'),
        updatedAt: new Date('2025-08-30T06:15:23.931Z'),
        memory: {
          id: 'memory-broken-gallery-2',
          title: 'Photo 2',
          description: 'Beautiful photo 2 from Broken Links Gallery',
          type: 'image',
          url: '/mock/galleries/broken-gallery/missing_photo_2.webp',
          createdAt: '2025-07-03T04:55:09.616Z',
          metadata: {},
        },
      },
      {
        id: 'item-broken-gallery-2',
        galleryId: 'broken-gallery',
        memoryId: 'memory-broken-gallery-3',
        memoryType: 'image',
        position: 2,
        caption: 'Photo 3',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-30T06:15:23.931Z'),
        updatedAt: new Date('2025-08-30T06:15:23.931Z'),
        memory: {
          id: 'memory-broken-gallery-3',
          title: 'Photo 3',
          description: 'Beautiful photo 3 from Broken Links Gallery',
          type: 'image',
          url: '/mock/galleries/broken-gallery/error_image_3.webp',
          createdAt: '2025-04-18T15:35:55.699Z',
          metadata: {},
        },
      },
      {
        id: 'item-broken-gallery-3',
        galleryId: 'broken-gallery',
        memoryId: 'memory-broken-gallery-4',
        memoryType: 'image',
        position: 3,
        caption: 'Photo 4',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-30T06:15:23.931Z'),
        updatedAt: new Date('2025-08-30T06:15:23.931Z'),
        memory: {
          id: 'memory-broken-gallery-4',
          title: 'Photo 4',
          description: 'Beautiful photo 4 from Broken Links Gallery',
          type: 'image',
          url: '/mock/galleries/broken-gallery/not_found_4.webp',
          createdAt: '2025-03-27T19:56:33.894Z',
          metadata: {},
        },
      },
      {
        id: 'item-broken-gallery-4',
        galleryId: 'broken-gallery',
        memoryId: 'memory-broken-gallery-5',
        memoryType: 'image',
        position: 4,
        caption: 'Photo 5',
        isFeatured: false,
        metadata: {},
        createdAt: new Date('2025-08-30T06:15:23.931Z'),
        updatedAt: new Date('2025-08-30T06:15:23.931Z'),
        memory: {
          id: 'memory-broken-gallery-5',
          title: 'Photo 5',
          description: 'Beautiful photo 5 from Broken Links Gallery',
          type: 'image',
          url: '/mock/galleries/broken-gallery/invalid_link_5.webp',
          createdAt: '2025-05-01T08:49:40.588Z',
          metadata: {},
        },
      },
    ],
    imageCount: 5,
    isOwner: true,
  },
];

export const getGeneratedGallery = (id: string): GalleryWithItems | undefined => {
  return generatedGalleries.find(gallery => gallery.id === id);
};

export const getAllGeneratedGalleries = (): GalleryWithItems[] => {
  return generatedGalleries;
};
